schema-version: 1.0
name: nodejs

ports:
  - "{{ port }}"

volumes:
  - app:{{ app }}:.

var:
  version: 12.18.3
  yarnVersion: 1.22.4
  app: /app
  port: "3000"
  user: default

provision:
  - url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}-linux-x64.tar.xz
  - url: https://github.com/yarnpkg/yarn/releases/download/v{{ yarnVersion }}/yarn-v{{ yarnVersion }}.tar.gz
  - systempath: /opt/node-v{{ version }}-linux-x64/bin
  - systempath: /opt/yarn-v{{ yarnVersion }}/bin
  - env: NODE_VERSION={{ version }}
  - env: NODE_PORT={{ port }}
  - user: "{{ user }}"

deploy:
  inputs:
    - app
  actions:
    - copy:
        input: app
        todir: "{{ app }}"
    - shell:
        inline: npm install
        directory: "{{ app }}"


command:
  node:
    inline: node {{ .args }}
    directory: "{{ app }}"
    user: "{{ user }}"
  npm:
    inline: npm {{ .args }}
    directory: "{{ app }}"
    user: "{{ user }}" 
  yarn:
    inline: yarn {{ .args }}
    directory: "{{ app }}"
    user: "{{ user }}"